import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import '@radix-ui/themes/styles.css';
// Radix UI themes
import { Theme} from '@radix-ui/themes'
import { ThemeProvider } from 'next-themes';
//global css



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, params: {locale}
}:{
  children: React.ReactNode, params: {locale: string};
}) {
  return (
    <html lang={locale} suppressHydrationWarning>
       <Theme data-is-root-theme='false' accentColor='plum' grayColor='mauve' scaling='100%' panelBackground='solid' >
      <body >
        {children}
      </body>
      </Theme>
    </html>
  );
}
